### ISSUE TITLE
Install location

### ISSUE THREAD

**Issue by ozum** [oclif/plugin-plugins#100]
Hi,

Thanks for the oclif and this plugin.

AFAIK plugins are installed in `~/.local`. For my workflow, I need to install runtime plugins into `node_modules` where main CLI is installed.

Is it possible to set install location?

Thanks,

**Comment by RasPhilCo** [comment]
You can used a scoped env var to set the data directory, ex: `HEROKU_DATA_DIR` (ref: https://github.com/oclif/config/blob/149529d07b15514add2d4e7453e10d204603ef1b/src/config.ts#L235).

**Comment by RasPhilCo** [comment]
Cleaning up - if you think this issue is still valid, reopen it. Thanks!
