### ISSUE TITLE
Programmatically install or detect installed plugins

### ISSUE THREAD

**Issue by alesanchezr** [oclif/plugin-plugins#238]
I'm developing a package called `learnpack` using the oclif framework.

The package work as a compiler for multiple languages (similar to webpack).

I'm using the plugin's plugin to delegate the work load of compiling, similar to how webpack plugins work (or its loaders):

If you install `learnpack` and you want to compile python language you also have to install the `learnpack-python` plugin like this:

```
$ learnpack plugins:install learnpack-python
```

My questions:

1. From my learnpack codebase, can I programmatically detect if the learnpack-python plugin was already installed? Right now I have a solution that feels hacky:

```js
          // run the `learnpack plugins` command on the shell
          let result = shell.exec('learnpack plugins', { silent: true })
          
          // check If the word "learnpack-python" exists on the stdout
          if(result.code == 0 && result.stdout.includes(`learnpack-${language}`)) return true;
          
          // if not, run command to install the plugin
          result = shell.exec(`learnpack plugins:install learnpack-${language}`, { silent: true })
          if(result.code === 0){
            Console.log(`Successfully installed the ${language} exercise engine`)
          } 
          else{
            Console.error(`Error installing ${language} exercise engine`)
          }
```

Maybe a hook can be developed to install packages programmatically?

**Comment by gonzaloriestra** [comment]
I've found a simpler way to find out if a plugin is installed. From a Command class you can check `this.config.plugins`, which contains a list of [Plugins](https://github.com/oclif/core/blob/main/src/interfaces/plugin.ts#L23), and you can check there if your plugin is in the list (with the `name` attribute for example).

**Comment by alesanchezr** [comment]
> I've found a simpler way to find out if a plugin is installed. From a Command class you can check `this.config.plugins`, which contains a list of [Plugins](https://github.com/oclif/core/blob/main/src/interfaces/plugin.ts#L23), and you can check there if your plugin is in the list (with the `name` attribute for example).

Thank you! will check it out!

**Comment by mdonnalley** [comment]
> I've found a simpler way to find out if a plugin is installed. From a Command class you can check `this.config.plugins`, which contains a list of [Plugins](https://github.com/oclif/core/blob/main/src/interfaces/plugin.ts#L23), and you can check there if your plugin is in the list (with the `name` attribute for example).

Closing this issue since checking `this.config.plugins` is the correct way to accomplish this
