### ISSUE TITLE
Friendly name package resolution fails if npm is not installed

### ISSUE THREAD

**Issue by tevanoff** [oclif/plugin-plugins#461]
Hello! An issue was recently reported on the Heroku CLI that we traced back to a subtle bug that was introduced in #283 

That change assumes that the `npm` command exists on the system. If that's not the case, as is possible with some Heroku CLI installs that bundle a version of node, the friendly name resolution will [silently fail](https://github.com/oclif/plugin-plugins/blob/3cbe6e7fc2e6959102b489bbba04dda4faf12832/src/plugins.ts#L253). When this happens, it can result in the entirely wrong package being installed as a plugin, which can fail in various ways that are not apparent and are hard to debug. 

Here's the CLI issue for more context: https://github.com/heroku/cli/issues/2034

What do you think about explicitly raising an exception if `npm` does not exist to make the dependency clear? Or, would it make sense to fall back to the `https` version of the check to avoid the dependency when it's not necessary?

Thanks!

**Comment by mdonnalley** [comment]
@tevanoff Thanks for finding the issue. We don't have bandwidth to prioritize a fix for this now but we're always happy to review and merge PRs if you'd like to submit one
