### ISSUE TITLE
Support standard NodeJS versions with NPM

### ISSUE THREAD

**Issue by hungrypipo** [oclif/plugin-plugins#625]
change npm version from ^9.7.2 to ^9.5.0 - so that the install just works seamlessly on standard npm versions

**Comment by hungrypipo** [comment]
Can this dependency be ignored by dependabot
@dependabot ignore this dependency
because in controlled environment npm can't be installed other than what is packaged with NodeJS versions

**Comment by mdonnalley** [comment]
`npm` is now ignored (see https://github.com/oclif/plugin-plugins/pull/647)
