### ISSUE TITLE
update hook fails silently on `yarn add` errors

### ISSUE THREAD

**Issue by ArchangelX360** [oclif/plugin-plugins#76]
`mycli update` triggers the `plugins:update` command, if the `plugins:update` fails on installation of a new plugin `yarn add ...`, then the update fails silently.

`mycli plugins:update` however displays the error as expected.

### Assumed root cause
The `update` hook is not catching error which makes the CLI update fails silently.

**Comment by RasPhilCo** [comment]
@ArchangelX360 I can't reproduce this behavior, any steps I can follow? Thanks!

**Comment by ArchangelX360** [comment]
Probably having a non-existing package to install in the plugins `package.json` will do the trick. The root cause is already identified and fixed in #77.

**Comment by RasPhilCo** [comment]
@ArchangelX360 got a chance to come back around on this. Two things: 1) I see the error displayed (not silent) when yarn add fails but 2) your PR prints the error better (I've made 1 small change request to remove the stack trace which is useless).
