### ISSUE TITLE
TypeError: Cannot read property 'dim' of undefined

### ISSUE THREAD

**Issue by shazron** [oclif/plugin-plugins#86]
## Log
```
$ ./bin/run plugins
TypeError: Cannot read property 'dim' of undefined
    at Object.<anonymous> (~/Desktop/package-2.2.1/node_modules/@oclif/color/lib/index.js:10:86)
    at Object.<anonymous> (~/Desktop/package-2.2.1/node_modules/@oclif/plugin-plugins/lib/commands/plugins/index.js:3:17)
```

## Expected
The plugins command successfully lists all the plugins. 

## Actual
An exception is logged.

## Cause
The `@oclif/color` module does not have `chalk` as a dependency in it's dependencies list in package.json in the npm released version `0.0.0` (there is no tag in the repo as well). This causes the null exception in the code above.

The code in `master` branch however, already has the required dependency.

## Fix
Release a new version of `@oclif/color` from the `master` branch code.

**Comment by RasPhilCo** [comment]
Clossed by https://github.com/oclif/color/commit/6df5f9dfd9eaae0fc1759167d683f0d1972c51f6

**Comment by shazron** [comment]
Can you re-open this? We are still seeing this issue.

Since this package specifies `@oclif/color` at `^0.0.0` it will *not* pick up `@oclif/color@0.1.0`
See: https://jubianchi.github.io/semver-check/#/^0.0.0/0.1.0 - at a glance I thought it would pick it up but apparently not.

**Comment by shazron** [comment]
See PR #92
