### ISSUE TITLE
`plugins --json` yields TypeError: Converting circular structure to JSON

### ISSUE THREAD

**Issue by justinwilaby** [oclif/plugin-plugins#876]
When using the `plugins --json` command, the following error occurs:
```
TypeError: Converting circular structure to JSON
        --> starting at object with constructor 'PluginLegacy'
        |     property 'config' -> object with constructor 'Config'
        |     property 'plugins' -> object with constructor 'Array'
        --- index 2 closes the circle
```
No json output is displayed.

// package.json
`"@oclif/plugin-plugins": "2.4.3",`

### Reproduction

1. Using Node 16, install the heroku cli globally: `npm i -g heroku`
2. install a plugin of some kind. e.g.: `heroku plugins:add @heroku-cli/plugin-data`
3. attempt to output json for plugin info: `heroku plugins --json`
4. Observe the above error is output.

**EDIT** This behavior is also confirmed with v5.1.2 and Node 22.x

**Comment by mdonnalley** [comment]
@justinwilaby Can you provide details on how to replicate? Thanks

**Comment by justinwilaby** [comment]
I've updated the initial issue with repro steps. Thank you for looking at this.

**Comment by mdonnalley** [comment]
@justinwilaby can you see if `5.1.3-qa.0` - resolves your issue?

**Comment by justinwilaby** [comment]
Yes it does! Yay! 

One complication here is that the Heroku team needs this backported to 2.x since we're still using node 16.x until at least the end of the year. Is this possible? I realize this may be a big ask since 3.x and 4.x may need this too.

**Comment by mdonnalley** [comment]
@justinwilaby We can consider it but how are you getting `--json` on 2.x? That flag was added in [3.1.0](https://github.com/oclif/plugin-plugins/releases/tag/3.1.0)

```
❯ heroku plugins --json
 ›   Error: Nonexistent flag: --json
 ›   See more help with --help
```

**Comment by justinwilaby** [comment]
Oh! Hmm.. You're absolutely right about that! I must have been looking at the wrong branch on my local. Yes, 3.x works.

On a side note, do you foresee any issues with using 5.x on a host application that's still on Node 16.x and @oclif/core v2.x? Backwards compatibility is a concern and thus the reason for the request.

**Comment by mdonnalley** [comment]
Just merged the PR - I'll port to 3.x here in a bit

**Comment by mdonnalley** [comment]
@justinwilaby 3.10.1 should have what you need
