### ISSUE TITLE
Commands as dependencies

### ISSUE THREAD

**Issue by yordis** [oclif/plugin-plugins#88]
I would like to install my CLI package and dependency with extra features.

```json
{
  "dependencies": {
    "my-cli": "latest",
    "my-cli-extra-commands": "latest"
  }
}
```

I am not sure what is the best approach to do this, do I suppose to use `scripts` to install the extra commands?

It would be good if we write some documentation about this use case if there is no documentation for it.

**Comment by RasPhilCo** [comment]
I may be misunderstanding you, but if you always want the extra commands included add them to your CLI as a plugin.

**Comment by yordis** [comment]
@RasPhilCo well, no always you want them to be included, that is why I am asking for a solution for this. 

Some packages would prefer to use Web commands added to the CLI, or End-to-End command, or any other kind of commands for example.

**Comment by RasPhilCo** [comment]
I'm still not sure what you're asking for: Users can add more commands to their CLI via `plugins:install`.

**Comment by yordis** [comment]
@RasPhilCo I understand that, I can use `package.scripts.postinstall`.

What would be a convenient way to register those commands? Is using `package.scripts.postinstall` what you are suggesting to use?

**Comment by mdonnalley** [comment]
Closing this issue since [plugins](https://oclif.io/docs/plugins) cover this functionality
