### ISSUE TITLE
Unable to `require('@oclif/plugin-plugins')` after tslib update

### ISSUE THREAD

**Issue by childish-sambino** [oclif/plugin-plugins#97]
Related to https://github.com/twilio/twilio-cli/issues/187

We take a dependency on the `Plugins` class to do some runtime package installations for various reasons. A recent update to the `tslib` dependency seems to have broken this integration. This statement is now returning an empty object: `require('@oclif/plugin-plugins')`.

Not a TS expert so I don't know what the proper fix is. Is it acceptable to update the index here to use a "named" export? Tested locally and looks to resolve the issue. E.g.
```
export { default } from './plugins'
```

**Comment by RasPhilCo** [comment]
Interesting! Want to explore with this more, I'll use the twilio-cli version in your issue.

**Comment by childish-sambino** [comment]
Note that because of https://github.com/oclif/plugin-plugins/pull/113 we've had to pin to `1.8.0` of this plugin.

**Comment by childish-sambino** [comment]
Actually, can't pin because of `npm audit` failures in the pipeline. Release is currently blocked.
